### ISSUE TITLE
How to get LLVM-IR from solidity?

### ISSUE THREAD

**Issue by hrshy0629** [matter-labs/compiler-llvm#2] opened 2023-04-09 06:22 UTC
I was researching, and I wanted to optimize a smart contract written in solidity using LLVM-related optimizers. However, I wasn't sure how to implement it until I read about this project. However, my knowledge of this project is still limited. I want to ask, for a single sol contract code, how can I get its LLVM-IR code? I looked at zksolc and failed. Do you have any suggestions?

**Comment by hedgar2017** [comment] 2023-04-13 09:14
@hrshy0629 duplicate of https://github.com/matter-labs/era-compiler-solidity/issues/2

**Closed as completed by hedgar2017** 2023-04-13 09:14 UTC
